apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helm-tiller
  namespace: kube-system
  labels:
    k8s-app: helm-tiller
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    matchLabels:
      k8s-app: helm-tiller
  template:
    metadata:
      labels:
        k8s-app: helm-tiller
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      containers:
          - name: helm-tiller
            image: gcr.io/kubernetes-helm/tiller:v2.0.0 
